### ISSUE TITLE
Feedback on week 13 project progress for CS2113-T13-3

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113-T13-3/main#216]
## Team progress for `v1.4`
* Milestone `v1.4` properly managed:
   * [ ] A suitable deadline set [your deadline: 2019-11-13] (:exclamation:)
   * [x] All issues in this milestone are closed(:heavy_check_mark: well done!)
   * [ ] Milestone explicitly closed(:exclamation:)
* [x] New JAR released on GitHub in the past 2 weeks (:heavy_check_mark: well done!)
## Individual progress of @fauzt for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T13-3/main/issues/188 https://github.com/AY1920S1-CS2113-T13-3/main/issues/176 https://github.com/AY1920S1-CS2113-T13-3/main/issues/153 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @hanskw4267 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T13-3/main/issues/188 https://github.com/AY1920S1-CS2113-T13-3/main/issues/181 https://github.com/AY1920S1-CS2113-T13-3/main/issues/173 https://github.com/AY1920S1-CS2113-T13-3/main/issues/148 https://github.com/AY1920S1-CS2113-T13-3/main/issues/146 https://github.com/AY1920S1-CS2113-T13-3/main/issues/108 https://github.com/AY1920S1-CS2113-T13-3/main/issues/81 (:heavy_check_mark: well done!)
* [x] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @assman for `v1.4`
* [ ] Merged updates to code (Java/FXML) files during the past 2 weeks (:exclamation:)
* [ ] Has issues assigned or PRs authored for `v1.4` milestone (:exclamation:)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @e0310898 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T13-3/main/issues/188 https://github.com/AY1920S1-CS2113-T13-3/main/issues/162 https://github.com/AY1920S1-CS2113-T13-3/main/issues/149 https://github.com/AY1920S1-CS2113-T13-3/main/issues/134 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @tanyixiang for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T13-3/main/issues/188 https://github.com/AY1920S1-CS2113-T13-3/main/issues/180 https://github.com/AY1920S1-CS2113-T13-3/main/issues/178 https://github.com/AY1920S1-CS2113-T13-3/main/issues/163 https://github.com/AY1920S1-CS2113-T13-3/main/issues/147 https://github.com/AY1920S1-CS2113-T13-3/main/issues/128 https://github.com/AY1920S1-CS2113-T13-3/main/issues/115 https://github.com/AY1920S1-CS2113-T13-3/main/issues/114 https://github.com/AY1920S1-CS2113-T13-3/main/issues/40 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)

Tutor: @RubaP

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-11-14 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
